/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Cart: () => import('#controllers/CartController'),
  Categories: () => import('#controllers/categories_controller'),
  Favorites: () => import('#controllers/favorites_controller'),
  MerchantDashboard: () => import('#controllers/merchant_dashboard_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  OrderTrackings: () => import('#controllers/order_trackings_controller'),
  Orders: () => import('#controllers/OrdersController'),
  Products: () => import('#controllers/products_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Reviews: () => import('#controllers/reviews_controller'),
  Session: () => import('#controllers/session_controller'),
  Users: () => import('#controllers/users_controller'),
}
