/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Blog: () => import('#controllers/blog_controller'),
  Cart: () => import('#controllers/CartController'),
  Categories: () => import('#controllers/categories_controller'),
  Coupons: () => import('#controllers/coupons_controller'),
  DashboardView: () => import('#controllers/dashboard_view_controller'),
  Favorites: () => import('#controllers/favorites_controller'),
  HealthChecks: () => import('#controllers/health_checks_controller'),
  MerchantDashboard: () => import('#controllers/merchant_dashboard_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  NewAccountControllers: () => import('#controllers/new_account_controllers'),
  Newsletter: () => import('#controllers/newsletter_controller'),
  OrderTrackings: () => import('#controllers/order_trackings_controller'),
  Orders: () => import('#controllers/OrdersController'),
  Products: () => import('#controllers/products_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Promotions: () => import('#controllers/promotions_controller'),
  Pubs: () => import('#controllers/pubs_controller'),
  PushSubscriptions: () => import('#controllers/push_subscriptions_controller'),
  Reviews: () => import('#controllers/reviews_controller'),
  Session: () => import('#controllers/session_controller'),
  SessionControllers: () => import('#controllers/session_controllers'),
  Users: () => import('#controllers/users_controller'),
}
