/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccessTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'updatedAt'] as const
  $columns = AccessTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AllTableSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'updatedAt'] as const
  $columns = AllTableSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CartItemSchema extends BaseModel {
  static $columns = ['cartId', 'createdAt', 'id', 'productId', 'quantity', 'updatedAt'] as const
  $columns = CartItemSchema.$columns
  @column()
  declare cartId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productId: number
  @column()
  declare quantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CartSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'updatedAt', 'userId'] as const
  $columns = CartSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'iconName', 'id', 'imageUrl', 'isActive', 'name', 'parentId', 'productCount', 'slug', 'sortOrder', 'updatedAt', 'userId'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare iconName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageUrl: string | null
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column()
  declare parentId: string | null
  @column()
  declare productCount: number | null
  @column()
  declare slug: string
  @column()
  declare sortOrder: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class CouponSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'description', 'discount', 'id', 'maximumDiscountAmount', 'minimumOrderAmount', 'productId', 'status', 'type', 'updatedAt', 'usageLimit', 'usedCount', 'userId', 'validFrom', 'validUntil'] as const
  $columns = CouponSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare discount: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maximumDiscountAmount: string | null
  @column()
  declare minimumOrderAmount: string | null
  @column()
  declare productId: number | null
  @column()
  declare status: string | null
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare usageLimit: number | null
  @column()
  declare usedCount: number | null
  @column()
  declare userId: number
  @column.dateTime()
  declare validFrom: DateTime | null
  @column.dateTime()
  declare validUntil: DateTime | null
}

export class FavoriteSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'productId', 'updatedAt', 'userId'] as const
  $columns = FavoriteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class OrderItemSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'id', 'image', 'orderId', 'price', 'productDescription', 'productId', 'productName', 'quantity', 'subtotal', 'updatedAt'] as const
  $columns = OrderItemSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare image: string | null
  @column()
  declare orderId: string
  @column()
  declare price: string
  @column()
  declare productDescription: string | null
  @column()
  declare productId: number | null
  @column()
  declare productName: string
  @column()
  declare quantity: number
  @column()
  declare subtotal: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderTrackingSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'location', 'orderId', 'status', 'trackedAt', 'updatedAt'] as const
  $columns = OrderTrackingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare location: string | null
  @column()
  declare orderId: string
  @column()
  declare status: string
  @column.dateTime()
  declare trackedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderSchema extends BaseModel {
  static $columns = ['billingAddress', 'createdAt', 'customerEmail', 'customerName', 'customerPhone', 'deliveredAt', 'deliveryMethod', 'estimatedDelivery', 'id', 'notes', 'orderNumber', 'paymentMethod', 'shippingAddress', 'shippingCost', 'status', 'subtotal', 'total', 'trackingNumber', 'updatedAt', 'userId'] as const
  $columns = OrderSchema.$columns
  @column()
  declare billingAddress: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare customerEmail: string
  @column()
  declare customerName: string
  @column()
  declare customerPhone: string | null
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare deliveryMethod: string | null
  @column.dateTime()
  declare estimatedDelivery: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare notes: string | null
  @column()
  declare orderNumber: string
  @column()
  declare paymentMethod: string
  @column()
  declare shippingAddress: string
  @column()
  declare shippingCost: string | null
  @column()
  declare status: string | null
  @column()
  declare subtotal: string | null
  @column()
  declare total: string
  @column()
  declare trackingNumber: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['category', 'categoryId', 'conservation', 'createdAt', 'description', 'id', 'imageUrl', 'isNew', 'isOnSale', 'name', 'oldPrice', 'origin', 'packaging', 'price', 'rating', 'reviewsCount', 'stock', 'updatedAt', 'userId', 'weight'] as const
  $columns = ProductSchema.$columns
  @column()
  declare category: string | null
  @column()
  declare categoryId: string | null
  @column()
  declare conservation: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column()
  declare isNew: boolean | null
  @column()
  declare isOnSale: boolean | null
  @column()
  declare name: string
  @column()
  declare oldPrice: string | null
  @column()
  declare origin: string | null
  @column()
  declare packaging: string | null
  @column()
  declare price: string
  @column()
  declare rating: string | null
  @column()
  declare reviewsCount: number | null
  @column()
  declare stock: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
  @column()
  declare weight: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt', 'uuid'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare uuid: string
}

export class WalletSchema extends BaseModel {
  static $columns = ['balance', 'createdAt', 'currency', 'id', 'status', 'updatedAt', 'userId'] as const
  $columns = WalletSchema.$columns
  @column()
  declare balance: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currency: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}
