/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AdminFeeSchema extends BaseModel {
  static $columns = ['adminId', 'amount', 'createdAt', 'id', 'orderId', 'orderNumber', 'percentage'] as const
  $columns = AdminFeeSchema.$columns
  @column()
  declare adminId: string | null
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare orderId: string
  @column()
  declare orderNumber: string
  @column()
  declare percentage: string
}

export class BlogPostSchema extends BaseModel {
  static $columns = ['authorId', 'authorName', 'category', 'content', 'createdAt', 'excerpt', 'id', 'imageUrl', 'metaDescription', 'metaTitle', 'publishedAt', 'readTime', 'slug', 'status', 'tags', 'title', 'updatedAt', 'views'] as const
  $columns = BlogPostSchema.$columns
  @column()
  declare authorId: string | null
  @column()
  declare authorName: string
  @column()
  declare category: string
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare excerpt: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageUrl: string | null
  @column()
  declare metaDescription: string | null
  @column()
  declare metaTitle: string | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare readTime: number | null
  @column()
  declare slug: string
  @column()
  declare status: string | null
  @column()
  declare tags: any | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare views: number | null
}

export class CartItemSchema extends BaseModel {
  static $columns = ['cartId', 'createdAt', 'id', 'productId', 'quantity', 'updatedAt'] as const
  $columns = CartItemSchema.$columns
  @column()
  declare cartId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productId: string
  @column()
  declare quantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CartSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'updatedAt', 'userId'] as const
  $columns = CartSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'iconName', 'id', 'imageUrl', 'isActive', 'name', 'parentId', 'productCount', 'productIds', 'slug', 'sortOrder', 'updatedAt', 'userId'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare iconName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageUrl: string | null
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column()
  declare parentId: string | null
  @column()
  declare productCount: number | null
  @column()
  declare productIds: any
  @column()
  declare slug: string
  @column()
  declare sortOrder: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class ContactSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'message', 'name', 'subject', 'updatedAt'] as const
  $columns = ContactSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare message: string
  @column()
  declare name: string
  @column()
  declare subject: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CouponSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'description', 'discount', 'id', 'maximumDiscountAmount', 'minimumOrderAmount', 'productId', 'status', 'type', 'updatedAt', 'usageLimit', 'usedCount', 'userId', 'userIds', 'validFrom', 'validUntil'] as const
  $columns = CouponSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare discount: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare maximumDiscountAmount: string | null
  @column()
  declare minimumOrderAmount: string | null
  @column()
  declare productId: string | null
  @column()
  declare status: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare usageLimit: number | null
  @column()
  declare usedCount: number | null
  @column()
  declare userId: string
  @column()
  declare userIds: any | null
  @column.dateTime()
  declare validFrom: DateTime | null
  @column.dateTime()
  declare validUntil: DateTime | null
}

export class FavoriteSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'productId', 'updatedAt', 'userId'] as const
  $columns = FavoriteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class KycSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'nomComplet', 'numeroTelephone', 'operateur', 'updatedAt'] as const
  $columns = KycSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nomComplet: string
  @column()
  declare numeroTelephone: string
  @column()
  declare operateur: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MerchantWithdrawalSchema extends BaseModel {
  static $columns = ['accountName', 'accountNumber', 'amount', 'createdAt', 'id', 'notes', 'operator', 'paymentMethod', 'processedAt', 'processedBy', 'reference', 'status', 'transactionId', 'updatedAt', 'userId'] as const
  $columns = MerchantWithdrawalSchema.$columns
  @column()
  declare accountName: string
  @column()
  declare accountNumber: string
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare notes: string | null
  @column()
  declare operator: string | null
  @column()
  declare paymentMethod: string
  @column.dateTime()
  declare processedAt: DateTime | null
  @column()
  declare processedBy: string | null
  @column()
  declare reference: string
  @column()
  declare status: string | null
  @column()
  declare transactionId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class NewsletterSubscriberSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id'] as const
  $columns = NewsletterSubscriberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
}

export class OrderItemSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'id', 'image', 'orderId', 'price', 'productDescription', 'productId', 'productName', 'quantity', 'subtotal', 'updatedAt'] as const
  $columns = OrderItemSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare image: string | null
  @column()
  declare orderId: string
  @column()
  declare price: string
  @column()
  declare productDescription: string | null
  @column()
  declare productId: string | null
  @column()
  declare productName: string
  @column()
  declare quantity: number
  @column()
  declare subtotal: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderTrackingSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'location', 'orderId', 'status', 'trackedAt', 'updatedAt'] as const
  $columns = OrderTrackingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare location: string | null
  @column()
  declare orderId: string
  @column()
  declare status: string
  @column.dateTime()
  declare trackedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderSchema extends BaseModel {
  static $columns = ['adminNotes', 'billingAddress', 'couponId', 'createdAt', 'customerEmail', 'customerName', 'customerPhone', 'deliveredAt', 'deliveryMethod', 'discountAmount', 'discountCode', 'estimatedDelivery', 'id', 'ipAddress', 'notes', 'orderNumber', 'paymentAmount', 'paymentCheckStatusUrl', 'paymentCompletedAt', 'paymentCurrency', 'paymentErrorMessage', 'paymentInitiatedAt', 'paymentMethod', 'paymentOperatorSimple', 'paymentReferenceId', 'paymentRetryCount', 'paymentStatus', 'paymentTransactionId', 'paymentXSecret', 'paymentXSecretExpiresIn', 'pickedUpAt', 'pickupCode', 'pickupStoreAddress', 'pickupStoreName', 'pickupStorePhone', 'shippingAddress', 'shippingCarrier', 'shippingConfirmedAt', 'shippingCost', 'shippingEstimatedDays', 'shippingTrackingUrl', 'status', 'subtotal', 'total', 'trackingNumber', 'updatedAt', 'userAgent', 'userId'] as const
  $columns = OrderSchema.$columns
  @column()
  declare adminNotes: string | null
  @column()
  declare billingAddress: string | null
  @column()
  declare couponId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare customerEmail: string
  @column()
  declare customerName: string
  @column()
  declare customerPhone: string | null
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare deliveryMethod: string
  @column()
  declare discountAmount: string | null
  @column()
  declare discountCode: string | null
  @column.dateTime()
  declare estimatedDelivery: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare notes: string | null
  @column()
  declare orderNumber: string
  @column()
  declare paymentAmount: string | null
  @column()
  declare paymentCheckStatusUrl: string | null
  @column.dateTime()
  declare paymentCompletedAt: DateTime | null
  @column()
  declare paymentCurrency: string | null
  @column()
  declare paymentErrorMessage: string | null
  @column.dateTime()
  declare paymentInitiatedAt: DateTime | null
  @column()
  declare paymentMethod: string
  @column()
  declare paymentOperatorSimple: string | null
  @column()
  declare paymentReferenceId: string | null
  @column()
  declare paymentRetryCount: number | null
  @column()
  declare paymentStatus: string | null
  @column()
  declare paymentTransactionId: string | null
  @column()
  declare paymentXSecret: string | null
  @column()
  declare paymentXSecretExpiresIn: number | null
  @column.dateTime()
  declare pickedUpAt: DateTime | null
  @column()
  declare pickupCode: string | null
  @column()
  declare pickupStoreAddress: string | null
  @column()
  declare pickupStoreName: string | null
  @column()
  declare pickupStorePhone: string | null
  @column()
  declare shippingAddress: string
  @column()
  declare shippingCarrier: string | null
  @column.dateTime()
  declare shippingConfirmedAt: DateTime | null
  @column()
  declare shippingCost: string | null
  @column()
  declare shippingEstimatedDays: number | null
  @column()
  declare shippingTrackingUrl: string | null
  @column()
  declare status: string | null
  @column()
  declare subtotal: string
  @column()
  declare total: string
  @column()
  declare trackingNumber: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string
}

export class OtpSchema extends BaseModel {
  static $columns = ['attempts', 'blockReason', 'blockedAt', 'createdAt', 'email', 'expiresAt', 'id', 'isBlocked', 'isUsed', 'otp', 'purpose', 'updatedAt', 'userId'] as const
  $columns = OtpSchema.$columns
  @column()
  declare attempts: number | null
  @column()
  declare blockReason: string | null
  @column.dateTime()
  declare blockedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isBlocked: boolean | null
  @column()
  declare isUsed: boolean | null
  @column()
  declare otp: string
  @column()
  declare purpose: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['category', 'categoryId', 'conservation', 'createdAt', 'description', 'id', 'imageUrl', 'imageUrl', 'isNew', 'isOnSale', 'isNew', 'isOnSale', 'name', 'origin', 'packaging', 'price', 'rating', 'stock', 'updatedAt', 'userId', 'weight'] as const
  $columns = ProductSchema.$columns
  @column()
  declare category: string | null
  @column()
  declare categoryId: string | null
  @column()
  declare conservation: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageUrl: string | null
  @column()
  declare isNew: boolean | null
  @column()
  declare isOnSale: boolean | null
  @column()
  declare name: string
  @column()
  declare origin: string | null
  @column()
  declare packaging: string | null
  @column()
  declare price: string
  @column()
  declare rating: number
  @column()
  declare stock: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare weight: string | null
}

export class PromotionSchema extends BaseModel {
  static $columns = ['bannerImage', 'buttonText', 'category', 'createdAt', 'description', 'discountAmount', 'discountPercentage', 'endDate', 'id', 'imageUrl', 'link', 'minOrderAmount', 'priority', 'productIds', 'startDate', 'status', 'title', 'type', 'updatedAt'] as const
  $columns = PromotionSchema.$columns
  @column()
  declare bannerImage: string | null
  @column()
  declare buttonText: string | null
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare discountAmount: number | null
  @column()
  declare discountPercentage: number | null
  @column.date()
  declare endDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageUrl: string | null
  @column()
  declare link: string | null
  @column()
  declare minOrderAmount: number | null
  @column()
  declare priority: number | null
  @column()
  declare productIds: string | null
  @column.date()
  declare startDate: DateTime | null
  @column()
  declare status: string | null
  @column()
  declare title: string
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PubSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'displayDuration', 'endDate', 'id', 'imageUrl', 'isActive', 'merchantId', 'name', 'priority', 'startDate', 'targetUrl', 'updatedAt'] as const
  $columns = PubSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string
  @column()
  declare displayDuration: number
  @column.dateTime()
  declare endDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageUrl: string
  @column()
  declare isActive: boolean | null
  @column()
  declare merchantId: string | null
  @column()
  declare name: string
  @column()
  declare priority: number | null
  @column.dateTime()
  declare startDate: DateTime | null
  @column()
  declare targetUrl: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PushSubscriptionSchema extends BaseModel {
  static $columns = ['auth', 'browser', 'createdAt', 'deviceId', 'deviceName', 'endpoint', 'id', 'isActive', 'os', 'p256Dh', 'swVersion', 'updatedAt'] as const
  $columns = PushSubscriptionSchema.$columns
  @column()
  declare auth: string
  @column()
  declare browser: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceId: string | null
  @column()
  declare deviceName: string | null
  @column()
  declare endpoint: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare os: string | null
  @column()
  declare p256Dh: string
  @column()
  declare swVersion: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ReviewSchema extends BaseModel {
  static $columns = ['comment', 'createdAt', 'helpfulCount', 'id', 'isVerifiedPurchase', 'merchantId', 'productId', 'rating', 'status', 'title', 'updatedAt', 'userId'] as const
  $columns = ReviewSchema.$columns
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare helpfulCount: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isVerifiedPurchase: boolean
  @column()
  declare merchantId: string | null
  @column()
  declare productId: string
  @column()
  declare rating: number
  @column()
  declare status: string
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class SecurityLogSchema extends BaseModel {
  static $columns = ['createdAt', 'duration', 'id', 'ip', 'method', 'referer', 'statusCode', 'url', 'userAgent'] as const
  $columns = SecurityLogSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare duration: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ip: string
  @column()
  declare method: string
  @column()
  declare referer: string | null
  @column()
  declare statusCode: number
  @column()
  declare url: string
  @column()
  declare userAgent: string | null
}

export class TestimonialSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'rating', 'text', 'updatedAt', 'userId'] as const
  $columns = TestimonialSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare rating: number
  @column()
  declare text: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class TransactionSchema extends BaseModel {
  static $columns = ['amount', 'balanceAfter', 'balanceBefore', 'completedAt', 'createdAt', 'description', 'id', 'metadata', 'reference', 'status', 'type', 'updatedAt', 'userId', 'walletId'] as const
  $columns = TransactionSchema.$columns
  @column()
  declare amount: string
  @column()
  declare balanceAfter: string
  @column()
  declare balanceBefore: string
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare metadata: any | null
  @column()
  declare reference: string
  @column()
  declare status: string | null
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
  @column()
  declare walletId: string | null
}

export class UserWithdrawalStatSchema extends BaseModel {
  static $columns = ['averageWithdrawal', 'completedAmount', 'completedCount', 'createdAt', 'failedAmount', 'failedCount', 'id', 'largestWithdrawal', 'lastWithdrawalAmount', 'lastWithdrawalAt', 'pendingAmount', 'pendingCount', 'totalAmount', 'totalWithdrawals', 'updatedAt', 'userId'] as const
  $columns = UserWithdrawalStatSchema.$columns
  @column()
  declare averageWithdrawal: string | null
  @column()
  declare completedAmount: string | null
  @column()
  declare completedCount: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare failedAmount: string | null
  @column()
  declare failedCount: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare largestWithdrawal: string | null
  @column()
  declare lastWithdrawalAmount: string | null
  @column.dateTime()
  declare lastWithdrawalAt: DateTime | null
  @column()
  declare pendingAmount: string | null
  @column()
  declare pendingCount: number | null
  @column()
  declare totalAmount: string | null
  @column()
  declare totalWithdrawals: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['acceptEscrow', 'accountHolderName', 'address', 'addressProofUrl', 'airtelNumber', 'avatar', 'bankName', 'birthDate', 'certifyTruth', 'commercialName', 'country', 'coverPhotoUrl', 'createdAt', 'email', 'facadePhoto1Url', 'facadePhoto2Url', 'facadePhoto1Url', 'facadePhoto2Url', 'facebookUrl', 'fullName', 'id', 'idBackUrl', 'idFrontUrl', 'idNumber', 'instagramUrl', 'interiorPhoto1Url', 'interiorPhoto2Url', 'interiorPhoto1Url', 'interiorPhoto2Url', 'isEmailVerified', 'isPhoneVerified', 'isVerified', 'isWhatsappVerified', 'logoUrl', 'moovNumber', 'neighborhood', 'nifNumber', 'password', 'paymentMethod', 'personalPhone', 'phone', 'rccmDocumentUrl', 'rccmNumber', 'reference1Name', 'reference1Phone', 'reference2Name', 'reference2Phone', 'reference1Name', 'reference1Phone', 'reference2Name', 'reference2Phone', 'rejectionReason', 'residenceAddress', 'ribDocumentUrl', 'role', 'seegOrLeaseUrl', 'selfieUrl', 'shopAddress', 'shopDescription', 'shopImage', 'shopLatitude', 'shopLongitude', 'shopName', 'signature', 'stockAddress', 'stockVideoUrl', 'tiktokUrl', 'updatedAt', 'vendorType', 'verificationStatus', 'verifiedAt', 'verifiedBy', 'whatsappPhone'] as const
  $columns = UserSchema.$columns
  @column()
  declare acceptEscrow: boolean | null
  @column()
  declare accountHolderName: string | null
  @column()
  declare address: string | null
  @column()
  declare addressProofUrl: string | null
  @column()
  declare airtelNumber: string | null
  @column()
  declare avatar: string | null
  @column()
  declare bankName: string | null
  @column.date()
  declare birthDate: DateTime | null
  @column()
  declare certifyTruth: boolean | null
  @column()
  declare commercialName: string | null
  @column()
  declare country: string | null
  @column()
  declare coverPhotoUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare facadePhoto1Url: string | null
  @column()
  declare facadePhoto2Url: string | null
  @column()
  declare facebookUrl: string | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare idBackUrl: string | null
  @column()
  declare idFrontUrl: string | null
  @column()
  declare idNumber: string | null
  @column()
  declare instagramUrl: string | null
  @column()
  declare interiorPhoto1Url: string | null
  @column()
  declare interiorPhoto2Url: string | null
  @column()
  declare isEmailVerified: boolean | null
  @column()
  declare isPhoneVerified: boolean | null
  @column()
  declare isVerified: boolean | null
  @column()
  declare isWhatsappVerified: boolean | null
  @column()
  declare logoUrl: string | null
  @column()
  declare moovNumber: string | null
  @column()
  declare neighborhood: string | null
  @column()
  declare nifNumber: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare paymentMethod: string | null
  @column()
  declare personalPhone: string | null
  @column()
  declare phone: string | null
  @column()
  declare rccmDocumentUrl: string | null
  @column()
  declare rccmNumber: string | null
  @column()
  declare reference1Name: string | null
  @column()
  declare reference1Phone: string | null
  @column()
  declare reference2Name: string | null
  @column()
  declare reference2Phone: string | null
  @column()
  declare rejectionReason: string | null
  @column()
  declare residenceAddress: string | null
  @column()
  declare ribDocumentUrl: string | null
  @column()
  declare role: string | null
  @column()
  declare seegOrLeaseUrl: string | null
  @column()
  declare selfieUrl: string | null
  @column()
  declare shopAddress: string | null
  @column()
  declare shopDescription: string | null
  @column()
  declare shopImage: string | null
  @column()
  declare shopLatitude: string | null
  @column()
  declare shopLongitude: string | null
  @column()
  declare shopName: string | null
  @column()
  declare signature: string | null
  @column()
  declare stockAddress: string | null
  @column()
  declare stockVideoUrl: string | null
  @column()
  declare tiktokUrl: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vendorType: string | null
  @column()
  declare verificationStatus: string | null
  @column.dateTime()
  declare verifiedAt: DateTime | null
  @column()
  declare verifiedBy: string | null
  @column()
  declare whatsappPhone: string | null
}

export class WalletSchema extends BaseModel {
  static $columns = ['balance', 'createdAt', 'currency', 'id', 'status', 'updatedAt', 'userId'] as const
  $columns = WalletSchema.$columns
  @column()
  declare balance: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currency: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class WithdrawalHistorySchema extends BaseModel {
  static $columns = ['action', 'amount', 'createdAt', 'id', 'ipAddress', 'metadata', 'newStatus', 'notes', 'oldStatus', 'performedBy', 'userId', 'withdrawalId'] as const
  $columns = WithdrawalHistorySchema.$columns
  @column()
  declare action: string
  @column()
  declare amount: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare metadata: any | null
  @column()
  declare newStatus: string
  @column()
  declare notes: string | null
  @column()
  declare oldStatus: string | null
  @column()
  declare performedBy: string | null
  @column()
  declare userId: string | null
  @column()
  declare withdrawalId: string | null
}

export class WithdrawalSchema extends BaseModel {
  static $columns = ['accountName', 'accountNumber', 'amount', 'bankName', 'createdAt', 'currency', 'externalReference', 'failureReason', 'fee', 'id', 'ipAddress', 'metadata', 'netAmount', 'notes', 'operator', 'paymentMethod', 'processedAt', 'processedBy', 'reference', 'status', 'transactionId', 'updatedAt', 'userAgent', 'userId', 'walletId'] as const
  $columns = WithdrawalSchema.$columns
  @column()
  declare accountName: string
  @column()
  declare accountNumber: string
  @column()
  declare amount: string
  @column()
  declare bankName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currency: string | null
  @column()
  declare externalReference: string | null
  @column()
  declare failureReason: string | null
  @column()
  declare fee: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare metadata: any | null
  @column()
  declare netAmount: string
  @column()
  declare notes: string | null
  @column()
  declare operator: string | null
  @column()
  declare paymentMethod: string
  @column.dateTime()
  declare processedAt: DateTime | null
  @column()
  declare processedBy: string | null
  @column()
  declare reference: string
  @column()
  declare status: string | null
  @column()
  declare transactionId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string | null
  @column()
  declare walletId: string | null
}
